glob: "app/**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: true
exclude:
  - '**/javascripts/*'
linters:
  HardCodedString:
    enabled: false
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
        EnforcedStyle: never
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
