# MySQL Configuration used for Github Actions
test:
  adapter: mysql2
  database: autolab_test
  pool: 5
  username: user
  password: password
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
