# MySQL Configuration used for Github Actions
production:
  adapter: mysql2
  database: autolab_test
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock
  host: mysql
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
